### ISSUE TITLE
Can't install chart torrent-http-proxy.

### ISSUE THREAD

**Issue by Blyster111** [webtor-io/helm-charts#1]
Hello. I'm installing helm charts, step by step from this tutorial, but it always fails at chart 'torrent-http-proxy'.

**Error:**
` Error: plugin "diff" exited with error
err 1: failed processing release torrent-http-proxy: helm exited with status 1:
  Error: Failed to render chart: exit status 1: Error: template: torrent-http-proxy/templates/ingress_grpc.yaml:1:14: executing "torrent-http-proxy/templates/ingress_grpc.yaml" at <.Values.ingressGRPC.enabled>: nil pointer evaluating interface {}.enabled`

I've looked for help on Google, tried on 2 servers, even tried to use the same helm and helmfile version as in the tutorial, always get the same error..
I also tried to add 'ingressGRPC' properties in 'helm-charts/charts/torrent-http-proxy/values.yaml' file, but it seems like after i call "helmfile update" it always ignores these files and gets them remotely or from an another location.

**helmfile -v**
helmfile version v0.102.0
**helm version**
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
**kubectl version**
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

![gif](https://user-images.githubusercontent.com/23199079/76683297-74e01900-6603-11ea-86a5-98d89b7414b1.gif)

**Comment by wlasser** [comment]
Same error. 
in ./helmfile.yaml: 2 errors:
err 0: failed processing release redis: helm exited with status 1:
  Error: Failed to render chart: exit status 1: Error: failed to download "stable/redis" (hint: running `helm repo update` may help)

  Error: plugin "diff" exited with error
err 1: failed processing release torrent-http-proxy: helm exited with status 1:
  Error: Failed to render chart: exit status 1: Error: template: torrent-http-proxy/templates/ingress_grpc.yaml:1:14: executing "torrent-http-proxy/templates/ingress_grpc.yaml" at <.Values.ingressGRPC.enabled>: nil pointer evaluating interface {}.enabled

  Error: plugin "diff" exited with error

**Comment by wlasser** [comment]
redis installation was fixed by 
helm repo add stable https://kubernetes-charts.storage.googleapis.com/

but don't understand 
Values.ingressGRPC.enabled

**Comment by vintikzzz** [comment]
@wlasser it is now possible to expose GRPC endpoint via ingress (I already use it in production). This endpoint might be used with php sdk.
