### ISSUE TITLE
[Question] Are there any alternative ways for setup (without docker/kubernetics and whatsoever)

### ISSUE THREAD

**Issue by FALL1N1** [webtor-io/helm-charts#10]
First, thank you for the project and hard work spent on it, I'm still learning it and I really appreciate it!

My question in general is that if I have a couple of bare-metal servers for example and I'd like to setup them as a single-node without docker, kubernetes and other virtualization-based stuff, how should we proceed?

This is only for testing (non-production) purposes, so firewalls/security-related issues are out of the question.
/my setup is purely lan-based and I got them in my garrage/

**Comment by vintikzzz** [comment]
@FALL1N1 Hi
Unfortunately there is no way to do so. Webtor was supposed to run only in Kubernetes environment and uses Kubernetes API's directly to manage workloads. It is quite simple to setup Kubernetes on bare-metal servers, so just give it a try.

**Comment by FALL1N1** [comment]
Thank you, I have installed Ubuntu 20.04 although the script seems outdated and no longer works, therefore this is one of the things I'd like to avoid. Perhaps it has something to do with ufw (the firewall)?


The errors are as follow:


```
in ./helmfile.yaml: 10 errors:
err 0: failed processing release magnet2torrent: microk8s.helm exited with status 1:
  Error: forwarding ports: error upgrading connection: error dialing backend: dial tcp xxx.xxx.xxx.xxx:10250: connect: connection refused
err 1: failed processing release redis: microk8s.helm exited with status 1:
  Error: forwarding ports: error upgrading connection: error dialing backend: dial tcp xxx.xxx.xxx.xxx:10250: connect: connection refused
err 2: failed processing release srt2vtt: microk8s.helm exited with status 1:
  Error: forwarding ports: error upgrading connection: error dialing backend: dial tcp xxx.xxx.xxx.xxx:10250: connect: connection refused
err 3: failed processing release video-info: microk8s.helm exited with status 1:
  Error: forwarding ports: error upgrading connection: error dialing backend: dial tcp xxx.xxx.xxx.xxx:10250: connect: connection refused
err 4: failed processing release external-proxy: microk8s.helm exited with status 1:
  Error: forwarding ports: error upgrading connection: error dialing backend: dial tcp xxx.xxx.xxx.xxx:10250: connect: connection refused
err 5: failed processing release torrent-store: microk8s.helm exited with status 1:
  Error: forwarding ports: error upgrading connection: error dialing backend: dial tcp xxx.xxx.xxx.xxx:10250: connect: connection refused
err 6: failed processing release torrent-archiver: microk8s.helm exited with status 1:
  Error: forwarding ports: error upgrading connection: error dialing backend: dial tcp xxx.xxx.xxx.xxx:10250: connect: connection refused
err 7: failed processing release content-prober: microk8s.helm exited with status 1:
  Error: forwarding ports: error upgrading connection: error dialing backend: dial tcp xxx.xxx.xxx.xxx:10250: connect: connection refused
err 8: failed processing release job-cleaner: microk8s.helm exited with status 1:
  Error: forwarding ports: error upgrading connection: error dialing backend: dial tcp xxx.xxx.xxx.xxx:10250: connect: connection refused
err 9: failed processing release torrent-http-proxy: microk8s.helm exited with status 1:
  Error: forwarding ports: error upgrading connection: error dialing backend: dial tcp xxx.xxx.xxx.xxx:10250: connect: connection refused
Error from server (NotFound): namespaces "webtor" not found
Error from server (NotFound): namespaces "webtor" not found

```

The full log output of the installer can be found here - https://pastebin.com/raw/TxmkTC5n


update::


Running it again though seems to kinda "install" it, this is the output:

Listening HTTP at port 31179
Listening HTTP at port 32189
Listening GRPC at port 30111


Although when I link the frontend to the API it does not seem to work, you can try with the following address 185.94.192.200

The output I get is: failed to pull torrent code=5

**Comment by FALL1N1** [comment]
Nevermind, seems to be an issue with the US Ubuntu repositories, some parts were not installed and after I ran everything one by one I managed to get it up and running, so if anyone else has issues with the repos - make sure to run everything command by command from the script and see where it times out.

Cheers and keep it up, I'll subscribe to your patreon right away, appreciated! :)
