### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by paulodbs** [webtor-io/helm-charts#11]
![image](https://user-images.githubusercontent.com/22200937/128433579-9ca36b0c-fbfe-44fe-b1ae-d975dcfe5e82.png)

**Comment by vintikzzz** [comment]
Hi @paulodbs 
The same issue was just resolved here #10

**Comment by paulodbs** [comment]
if i provide a VPS for you to install could you record a video installing? would help a lot for me and future people.

**Comment by FALL1N1** [comment]
@paulodbs hey, I managed to fix it by replacing Ubuntu's repositories by the local ones - e.g "https://us.ubuntu..." to "https://ubuntu...", then upgrade/update.

Once ready, run the script once and then again command by command, once done - it will work like a charm.

**Comment by paulodbs** [comment]
I'm having a problem on the front end, it's not specifying how to install

**Comment by FALL1N1** [comment]
This repository is for the backend, for the front end you need https://github.com/webtor-io/platform-sdk-js/tree/master/example this for example unless you need any other language.
You need NodeJS too.

It's quite simple, clone the repo, run "npm install" in it so it can install it's dependencies, edit the URL at https://github.com/webtor-io/platform-sdk-js/blob/master/example/src/index.js#L27 then "npm run build" and open the "index.html".

**Comment by FALL1N1** [comment]
Although, the script might have to be re-done, sometimes it install it, sometimes not and it's unrelated to the OS.

Fresh Ubuntu 20.04 install, 

Listening HTTP at port 32627
Listening HTTP at port 32669
Listening GRPC at port 31488


root@node:~# curl -I 127.0.0.1:31488
curl: (1) Received HTTP/0.9 when not allowed

**Comment by vintikzzz** [comment]
it is not good idea to use curl with grpc. Just try curl on 32627 port.

**Comment by PenguinChief** [comment]
same issue.
I'm not very knowledgeable about servers, can someone guide me?

```shell
in ./helmfile.yaml: 10 errors:
err 0: failed processing release torrent-archiver: microk8s.helm exited with status 1:
  Error: could not find a ready tiller pod
err 1: failed processing release torrent-http-proxy: microk8s.helm exited with status 1:
  Error: could not find a ready tiller pod
err 2: failed processing release magnet2torrent: microk8s.helm exited with status 1:
  Error: could not find a ready tiller pod
err 3: failed processing release content-prober: microk8s.helm exited with status 1:
  Error: could not find a ready tiller pod
err 4: failed processing release srt2vtt: microk8s.helm exited with status 1:
  Error: could not find a ready tiller pod
err 5: failed processing release torrent-store: microk8s.helm exited with status 1:
  Error: could not find a ready tiller pod
err 6: failed processing release redis: microk8s.helm exited with status 1:
  Error: could not find a ready tiller pod
err 7: failed processing release external-proxy: microk8s.helm exited with status 1:
  Error: could not find a ready tiller pod
err 8: failed processing release job-cleaner: microk8s.helm exited with status 1:
  Error: could not find a ready tiller pod
err 9: failed processing release video-info: microk8s.helm exited with status 1:
  Error: could not find a ready tiller pod
Error from server (NotFound): namespaces "webtor" not found
Error from server (NotFound): namespaces "webtor" not found
```

**Comment by PenguinChief** [comment]
When install with "Long way"
After run step "7. Run Helmfile"
```shell
helmfile apply
```
I have error like that.
![image](https://user-images.githubusercontent.com/18276928/138711283-fc04529b-15a4-48fd-bda4-19d6c97a9c92.png)

**Comment by deorder** [comment]
> 
> 
> When install with "Long way" After run step "7. Run Helmfile"
> 
> ```shell
> helmfile apply
> ```
> 
> I have error like that. ![image](https://user-images.githubusercontent.com/18276928/138711283-fc04529b-15a4-48fd-bda4-19d6c97a9c92.png)

Use the changes in my pull request:
https://github.com/webtor-io/helm-charts/pull/12

**Comment by vintikzzz** [comment]
@deorder Hi! Just update helmfile.yaml from repo
