### ISSUE TITLE
webtor-web-ui image source code

### ISSUE THREAD

**Issue by rgl** [webtor-io/helm-charts#14]
Where is the source code for the webtor-web-ui image used at https://github.com/webtor-io/helm-charts/tree/master/charts/webtor-web-ui?

**Comment by vintikzzz** [comment]
This is the image of webtor.io UI and I am not planning to opensource it right now. You can build your own player on top of [platform-sdk-js](https://github.com/webtor-io/platform-sdk-js) see [examples](https://github.com/webtor-io/platform-sdk-js/tree/master/example)

**Comment by rgl** [comment]
Understood! Thanks for clearing this up.
