### ISSUE TITLE
its show this

### ISSUE THREAD

**Issue by jeffvffv** [webtor-io/helm-charts#16]
Error: looks like "https://charts.webtor.io" is not a valid chart repository or cannot be reached: failed to fetch https://charts.webtor.io/index.yaml : 503 Service Unavailable

**Comment by fglkdjmnml** [comment]
It sometimes happens so I created a github page for it, you can also use it by opening helmfile.yaml in a text editor and edit url from https://charts.webtor.io/ to https://fglkdjmnml.github.io/hfghfgh/ then do `helmfile apply`
