### ISSUE TITLE
Dockerize

### ISSUE THREAD

**Issue by FedeJure** [webtor-io/helm-charts#3]
great job! it is possible to dockerize this backend? it would be much easy to get it run. TY! Great work

**Comment by vintikzzz** [comment]
Hi! Every component is already dockerized on it's own. From the very beginning this backend was designed to be scalable and be able to run on multiple nodes in kubernetes environment. But I understand that it is quite hard to setup it. I thought about single setup script but it is not ready yet.

**Comment by vintikzzz** [comment]
Single script is ready. Please check README.md.

**Comment by FedeJure** [comment]
Works like a charm!! ty!
