### ISSUE TITLE
Something gone bad

### ISSUE THREAD

**Issue by wlasser** [webtor-io/helm-charts#4]
I don't know, why and when this happens - but now i am have:

`torrent-http-proxy-khf85            0/1     CrashLoopBackOff   9          35m
`
Any solution?

**Comment by wlasser** [comment]
`kubectl logs torrent-http-proxy-khf85 -n webtor
{"message":"Serving GRPC at :50051","severity":"INFO","timestamp":{"seconds":159                                           7941941,"nanos":375593916}}
{"message":"Serving Probe at :8081","severity":"INFO","timestamp":{"seconds":159                                           7941941,"nanos":375710330}}
{"message":"Serving Web at :8080","severity":"INFO","timestamp":{"seconds":15979                                           41941,"nanos":375910001}}
{"Host":"5.135.154.70:9989","InfoHash":"magnet2torrent","Path":"/Magnet2Torrent/                                           Magnet2Torrent","URL":"/magnet2torrent/Magnet2Torrent/Magnet2Torrent","message":                                           "Handling GRPC WebSocket Request","severity":"INFO","timestamp":{"seconds":15979                                           42048,"nanos":951382599}}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1210686]

goroutine 58 [running]:
github.com/webtor-io/torrent-http-proxy/services.(*GRPCProxy).get.func1(0x16dc7e                                           0, 0xc000319830, 0xc0001ac2a0, 0x1e, 0x7fadc1e3a801, 0x7fadc2019fff, 0xc00037eac                                           0, 0x417a7c, 0x7fadc1e3a700)
        /app/services/grpc_proxy.go:99 +0x8e6
github.com/mwitkow/grpc-proxy/proxy.(*handler).handler(0xc000186110, 0x0, 0x0, 0                                           x16e3d60, 0xc00040e000, 0x30, 0x1402420)
        /app/vendor/github.com/mwitkow/grpc-proxy/proxy/handler.go:67 +0xd4
github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func2(0x0, 0x0, 0                                           x16e3d60, 0xc00040e000, 0xc0003361c0, 0xc00018e470, 0x16dc7e0, 0xc000319830)
        /app/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:89 +0x                                           4e
google.golang.org/grpc.(*Server).processStreamingRPC(0xc000194900, 0x16ecca0, 0x                                           c0003686c0, 0xc000343300, 0x0, 0xc000182340, 0x0, 0x0, 0x0)
        /app/vendor/google.golang.org/grpc/server.go:1218 +0x48e
google.golang.org/grpc.(*Server).handleStream(0xc000194900, 0x16ecca0, 0xc000368                                           6c0, 0xc000343300, 0x0)
        /app/vendor/google.golang.org/grpc/server.go:1297 +0xbb0
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000314470, 0xc000194900                                           , 0x16ecca0, 0xc0003686c0, 0xc000343300)
        /app/vendor/google.golang.org/grpc/server.go:722 +0xa1
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /app/vendor/google.golang.org/grpc/server.go:720 +0xa1
`

**Comment by vintikzzz** [comment]
Hi!
Fixed in https://github.com/webtor-io/torrent-http-proxy/commit/5f38109fd5e053b3e27c224b80c86a4912f13ebc

**Comment by wlasser** [comment]
Hello!
There is no comming updates.
git pull in charts repo no delivered new updates
updated helm repo
but 
`No affected releases`

**Comment by wlasser** [comment]
@vintikzzz 
Pavel, hello.
I am fully remove minikube, reinstall with helm, but still have broken webtor:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1210686]

goroutine 41 [running]:
github.com/webtor-io/torrent-http-proxy/services.(*GRPCProxy).get.func1(0x16dc7e0, 0xc000304de0, 0xc00030e160, 0x1e, 0x7f2f1ddf6301, 0x7f2f1dfdafff, 0xc000102ac0, 0x417a7c, 0x7f2f1ddf6200)
        /app/services/grpc_proxy.go:99 +0x8e6
github.com/mwitkow/grpc-proxy/proxy.(*handler).handler(0xc0003100b0, 0x0, 0x0, 0x16e3d60, 0xc000364000, 0x30, 0x1402420)
        /app/vendor/github.com/mwitkow/grpc-proxy/proxy/handler.go:67 +0xd4
github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func2(0x0, 0x0, 0x16e3d60, 0xc000364000, 0xc000322400, 0xc0003063b0, 0x16dc7e0, 0xc000304de0)
        /app/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:89 +0x4e
google.golang.org/grpc.(*Server).processStreamingRPC(0xc000338780, 0x16ecca0, 0xc0003322d0, 0xc00033c500, 0x0, 0xc000322280, 0x0, 0x0, 0x0)
        /app/vendor/google.golang.org/grpc/server.go:1218 +0x48e
google.golang.org/grpc.(*Server).handleStream(0xc000338780, 0x16ecca0, 0xc0003322d0, 0xc00033c500, 0x0)
        /app/vendor/google.golang.org/grpc/server.go:1297 +0xbb0
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000300270, 0xc000338780, 0x16ecca0, 0xc0003322d0, 0xc00033c500)
        /app/vendor/google.golang.org/grpc/server.go:722 +0xa1
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /app/vendor/google.golang.org/grpc/server.go:720 +0xa1
```

**Comment by wlasser** [comment]
with latest updates - nothing is changed:
```
kubectl logs torrent-http-proxy-4lp8w -n webtor
{"message":"Serving Probe at :8081","severity":"INFO","timestamp":{"seconds":1600069432,"nanos":655394270}}
{"message":"Serving GRPC at :50051","severity":"INFO","timestamp":{"seconds":1600069432,"nanos":655911709}}
{"message":"Serving Web at :8080","severity":"INFO","timestamp":{"seconds":1600069432,"nanos":656124019}}
{"Host":"store.goodway.xyz:30174","InfoHash":"magnet2torrent","Path":"/Magnet2Torrent/Magnet2Torrent","URL":"/magnet2torrent/Magnet2Torrent/Magnet2Torrent","message":"Handling GRPC WebSocket Request","severity":"INFO","timestamp":{"seconds":1600069441,"nanos":881901993}}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1210686]

goroutine 54 [running]:
github.com/webtor-io/torrent-http-proxy/services.(*GRPCProxy).get.func1(0x16dc7e0, 0xc000394d80, 0xc0003a6160, 0x1e, 0x7fe0054f9c01, 0x7fe0056d9fff, 0xc00009dac0, 0x417a7c, 0x7fe0054f9b00)
        /app/services/grpc_proxy.go:99 +0x8e6
github.com/mwitkow/grpc-proxy/proxy.(*handler).handler(0xc0003ac0a0, 0x0, 0x0, 0x16e3d60, 0xc0003f6000, 0x30, 0x1402420)
        /app/vendor/github.com/mwitkow/grpc-proxy/proxy/handler.go:67 +0xd4
github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func2(0x0, 0x0, 0x16e3d60, 0xc0003f6000, 0xc00039e400, 0xc000396440, 0x16dc7e0, 0xc000394d80)
        /app/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:89 +0x4e
google.golang.org/grpc.(*Server).processStreamingRPC(0xc0003c0480, 0x16ecca0, 0xc0003ba240, 0xc0003cc400, 0x0, 0xc00039e280, 0x0, 0x0, 0x0)
        /app/vendor/google.golang.org/grpc/server.go:1218 +0x48e
google.golang.org/grpc.(*Server).handleStream(0xc0003c0480, 0x16ecca0, 0xc0003ba240, 0xc0003cc400, 0x0)
        /app/vendor/google.golang.org/grpc/server.go:1297 +0xbb0
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000390210, 0xc0003c0480, 0x16ecca0, 0xc0003ba240, 0xc0003cc400)
        /app/vendor/google.golang.org/grpc/server.go:722 +0xa1
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /app/vendor/google.golang.org/grpc/server.go:720 +0xa1
```

**Comment by vintikzzz** [comment]
Try to set in helmfile `pullPolicy: Always` and apply helmfile
```
- name: torrent-http-proxy
  namespace: webtor
  chart: webtor/torrent-http-proxy
  version: 0.1.0
  values:
    - image:
        pullPolicy: Always
```
So this should force to load latest image from dockerhub

**Comment by wlasser** [comment]
@vintikzzz with this changes - all is looking good. Thank you.
