### ISSUE TITLE
failed to download "stable/redis" - >> helmfile apply

### ISSUE THREAD

**Issue by tmu7ammed** [webtor-io/helm-charts#5]
$ sudo helmfile apply
Comparing release=redis, chart=stable/redis
Comparing release=torrent-store, chart=webtor/torrent-store
Comparing release=content-prober, chart=webtor/content-prober
Comparing release=external-proxy, chart=webtor/external-proxy
Comparing release=video-info, chart=webtor/video-info
Comparing release=torrent-archiver, chart=webtor/torrent-archiver
Comparing release=srt2vtt, chart=webtor/srt2vtt
Comparing release=torrent-http-proxy, chart=webtor/torrent-http-proxy
Comparing release=magnet2torrent, chart=webtor/magnet2torrent
********************

        Release was not present in Helm.  Diff will show entire contents as new.

********************
webtor, torrent-store, Deployment (apps) has been added:
-
+ # Source: torrent-store/templates/deployment.yaml
+ apiVersion: apps/v1
+ kind: Deployment
+ metadata:
+   name: torrent-store
+   labels:
+     app.kubernetes.io/name: torrent-store
+     helm.sh/chart: torrent-store-0.1.0
+     app.kubernetes.io/instance: torrent-store
+     app.kubernetes.io/managed-by: Helm
+ spec:
+   replicas: 1
+   selector:
+     matchLabels:
+       app.kubernetes.io/name: torrent-store
+       app.kubernetes.io/instance: torrent-store
+   template:
+     metadata:
+       labels:
+         app.kubernetes.io/name: torrent-store
+         app.kubernetes.io/instance: torrent-store
+     spec:
+       containers:
+         - name: torrent-store
+           image: "webtor/torrent-store:latest"
+           imagePullPolicy: IfNotPresent
+           ports:
+             - name: grpc
+               containerPort: 50051
+               protocol: TCP
+           livenessProbe:
+             tcpSocket:
+               port: grpc
+           readinessProbe:
+             tcpSocket:
+               port: grpc
+           resources:
+             {}
webtor, torrent-store, Service (v1) has been added:
-
+ # Source: torrent-store/templates/service.yaml
+ apiVersion: v1
+ kind: Service
+ metadata:
+   name: torrent-store
+   labels:
+     app.kubernetes.io/name: torrent-store
+     helm.sh/chart: torrent-store-0.1.0
+     app.kubernetes.io/instance: torrent-store
+     app.kubernetes.io/managed-by: Helm
+ spec:
+   type: ClusterIP
+   ports:
+     - port: 50051
+       targetPort: grpc
+       protocol: TCP
+       name: grpc
+   selector:
+     app.kubernetes.io/name: torrent-store
+     app.kubernetes.io/instance: torrent-store

********************

        Release was not present in Helm.  Diff will show entire contents as new.

********************
webtor, torrent-archiver, Deployment (apps) has been added:
-
+ # Source: torrent-archiver/templates/deployment.yaml
+ apiVersion: apps/v1
+ kind: Deployment
+ metadata:
+   name: torrent-archiver
+   labels:
+     app.kubernetes.io/name: torrent-archiver
+     helm.sh/chart: torrent-archiver-0.1.0
+     app.kubernetes.io/instance: torrent-archiver
+     app.kubernetes.io/managed-by: Helm
+ spec:
+   replicas: 1
+   selector:
+     matchLabels:
+       app.kubernetes.io/name: torrent-archiver
+       app.kubernetes.io/instance: torrent-archiver
+   template:
+     metadata:
+       labels:
+         app.kubernetes.io/name: torrent-archiver
+         app.kubernetes.io/instance: torrent-archiver
+     spec:
+       containers:
+         - name: torrent-archiver
+           image: "webtor/torrent-archiver:latest"
+           imagePullPolicy: IfNotPresent
+           ports:
+             - name: http
+               containerPort: 8080
+               protocol: TCP
+             - name: httpprobe
+               containerPort: 8081
+               protocol: TCP
+           livenessProbe:
+             httpGet:
+               path: /liveness
+               port: httpprobe
+           readinessProbe:
+             httpGet:
+               path: /readiness
+               port: httpprobe
+           resources:
+             {}
webtor, torrent-archiver, Service (v1) has been added:
-
+ # Source: torrent-archiver/templates/service.yaml
+ apiVersion: v1
+ kind: Service
+ metadata:
+   name: torrent-archiver
+   labels:
+     app.kubernetes.io/name: torrent-archiver
+     helm.sh/chart: torrent-archiver-0.1.0
+     app.kubernetes.io/instance: torrent-archiver
+     app.kubernetes.io/managed-by: Helm
+ spec:
+   type: ClusterIP
+   ports:
+     - port: 80
+       targetPort: http
+       protocol: TCP
+       name: http
+   selector:
+     app.kubernetes.io/name: torrent-archiver
+     app.kubernetes.io/instance: torrent-archiver

********************

        Release was not present in Helm.  Diff will show entire contents as new.

********************
webtor, video-info, DaemonSet (apps) has been added:
-
+ # Source: video-info/templates/daemonset.yaml
+ apiVersion: apps/v1
+ kind: DaemonSet
+ metadata:
+   name: video-info
+   labels:
+     app.kubernetes.io/name: video-info
+     helm.sh/chart: video-info-0.1.0
+     app.kubernetes.io/instance: video-info
+     app.kubernetes.io/managed-by: Helm
+ spec:
+   selector:
+     matchLabels:
+       app.kubernetes.io/name: video-info
+       app.kubernetes.io/instance: video-info
+   template:
+     metadata:
+       labels:
+         app.kubernetes.io/name: video-info
+         app.kubernetes.io/instance: video-info
+     spec:
+       containers:
+         - name: video-info
+           image: "webtor/video-info:latest"
+           imagePullPolicy: IfNotPresent
+           ports:
+             - name: http
+               containerPort: 8080
+               protocol: TCP
+             - name: httpprobe
+               containerPort: 8081
+               protocol: TCP
+           livenessProbe:
+             httpGet:
+               path: /liveness
+               port: httpprobe
+           readinessProbe:
+             httpGet:
+               path: /readiness
+               port: httpprobe
+           resources:
+             {}
webtor, video-info, Service (v1) has been added:
-
+ # Source: video-info/templates/service.yaml
+ apiVersion: v1
+ kind: Service
+ metadata:
+   name: video-info
+   labels:
+     app.kubernetes.io/name: video-info
+     helm.sh/chart: video-info-0.1.0
+     app.kubernetes.io/instance: video-info
+     app.kubernetes.io/managed-by: Helm
+ spec:
+   type: ClusterIP
+   ports:
+     - port: 80
+       targetPort: http
+       protocol: TCP
+       name: http
+   selector:
+     app.kubernetes.io/name: video-info
+     app.kubernetes.io/instance: video-info

********************

        Release was not present in Helm.  Diff will show entire contents as new.

********************
webtor, content-prober, Deployment (apps) has been added:
-
+ # Source: content-prober/templates/deployment.yaml
+ apiVersion: apps/v1
+ kind: Deployment
+ metadata:
+   name: content-prober
+   labels:
+     app.kubernetes.io/name: content-prober
+     helm.sh/chart: content-prober-0.1.0
+     app.kubernetes.io/instance: content-prober
+     app.kubernetes.io/managed-by: Helm
+ spec:
+   replicas: 1
+   selector:
+     matchLabels:
+       app.kubernetes.io/name: content-prober
+       app.kubernetes.io/instance: content-prober
+   template:
+     metadata:
+       labels:
+         app.kubernetes.io/name: content-prober
+         app.kubernetes.io/instance: content-prober
+     spec:
+       containers:
+         - name: content-prober
+           image: "webtor/content-prober:latest"
+           imagePullPolicy: IfNotPresent
+           ports:
+             - name: grpc
+               containerPort: 50051
+               protocol: TCP
+           livenessProbe:
+             tcpSocket:
+               port: grpc
+           readinessProbe:
+             tcpSocket:
+               port: grpc
+           resources:
+             {}
webtor, content-prober, Service (v1) has been added:
-
+ # Source: content-prober/templates/service.yaml
+ apiVersion: v1
+ kind: Service
+ metadata:
+   name: content-prober
+   labels:
+     app.kubernetes.io/name: content-prober
+     helm.sh/chart: content-prober-0.1.0
+     app.kubernetes.io/instance: content-prober
+     app.kubernetes.io/managed-by: Helm
+ spec:
+   type: ClusterIP
+   ports:
+     - port: 50051
+       targetPort: grpc
+       protocol: TCP
+       name: grpc
+   selector:
+     app.kubernetes.io/name: content-prober
+     app.kubernetes.io/instance: content-prober

********************

        Release was not present in Helm.  Diff will show entire contents as new.

********************
webtor, external-proxy, Deployment (apps) has been added:
-
+ # Source: external-proxy/templates/deployment.yaml
+ apiVersion: apps/v1
+ kind: Deployment
+ metadata:
+   name: external-proxy
+   labels:
+     app.kubernetes.io/name: external-proxy
+     helm.sh/chart: external-proxy-0.1.0
+     app.kubernetes.io/instance: external-proxy
+     app.kubernetes.io/managed-by: Helm
+ spec:
+   replicas: 1
+   selector:
+     matchLabels:
+       app.kubernetes.io/name: external-proxy
+       app.kubernetes.io/instance: external-proxy
+   template:
+     metadata:
+       labels:
+         app.kubernetes.io/name: external-proxy
+         app.kubernetes.io/instance: external-proxy
+     spec:
+       containers:
+         - name: external-proxy
+           image: "webtor/external-proxy:latest"
+           imagePullPolicy: IfNotPresent
+           ports:
+             - name: http
+               containerPort: 8080
+               protocol: TCP
+             - name: httpprobe
+               containerPort: 8081
+               protocol: TCP
+           livenessProbe:
+             httpGet:
+               path: /liveness
+               port: httpprobe
+           readinessProbe:
+             httpGet:
+               path: /readiness
+               port: httpprobe
+           resources:
+             {}
webtor, external-proxy, Service (v1) has been added:
-
+ # Source: external-proxy/templates/service.yaml
+ apiVersion: v1
+ kind: Service
+ metadata:
+   name: external-proxy
+   labels:
+     app.kubernetes.io/name: external-proxy
+     helm.sh/chart: external-proxy-0.1.0
+     app.kubernetes.io/instance: external-proxy
+     app.kubernetes.io/managed-by: Helm
+ spec:
+   type: ClusterIP
+   ports:
+     - port: 80
+       targetPort: http
+       protocol: TCP
+       name: http
+   selector:
+     app.kubernetes.io/name: external-proxy
+     app.kubernetes.io/instance: external-proxy

********************

        Release was not present in Helm.  Diff will show entire contents as new.

********************
webtor, torrent-http-proxy, ClusterRole (rbac.authorization.k8s.io) has been added:
-
+ # Source: torrent-http-proxy/templates/rbac.yaml
+ kind: ClusterRole
+ apiVersion: rbac.authorization.k8s.io/v1
+ metadata:
+   labels:
+     app: torrent-http-proxy
+     chart: torrent-http-proxy-0.1.0
+     heritage: Helm
+     release: torrent-http-proxy
+   name: torrent-http-proxy
+ rules:
+ - apiGroups: [""]
+   resources: ["pods"]
+   verbs: ["list", "watch", "delete"]
+ - apiGroups: [""]
+   resources: ["nodes"]
+   verbs: ["list"]
+ - apiGroups: ["batch", "extensions"]
+   resources: ["jobs"]
+   verbs: ["list", "create", "watch", "delete"]
webtor, torrent-http-proxy, ClusterRoleBinding (rbac.authorization.k8s.io) has been added:
-
+ # Source: torrent-http-proxy/templates/rbac.yaml
+ apiVersion: rbac.authorization.k8s.io/v1beta1
+ kind: ClusterRoleBinding
+ metadata:
+   labels:
+     app: torrent-http-proxy
+     chart: torrent-http-proxy-0.1.0
+     heritage: Helm
+     release: torrent-http-proxy
+   name: torrent-http-proxy
+ roleRef:
+   apiGroup: rbac.authorization.k8s.io
+   kind: ClusterRole
+   name: torrent-http-proxy
+ subjects:
+   - kind: ServiceAccount
+     name: default
+     namespace: webtor
webtor, torrent-http-proxy, ConfigMap (v1) has been added:
-
+ # Source: torrent-http-proxy/templates/configmap.yaml
+ apiVersion: v1
+ kind: ConfigMap
+ metadata:
+   name: torrent-http-proxy
+   labels:
+     app.kubernetes.io/name: torrent-http-proxy
+     helm.sh/chart: torrent-http-proxy-0.1.0
+     app.kubernetes.io/instance: torrent-http-proxy
+     app.kubernetes.io/managed-by: Helm
+ data:
webtor, torrent-http-proxy, DaemonSet (apps) has been added:
-
+ # Source: torrent-http-proxy/templates/daemonset.yaml
+ apiVersion: apps/v1
+ kind: DaemonSet
+ metadata:
+   name: torrent-http-proxy
+   labels:
+     app.kubernetes.io/name: torrent-http-proxy
+     helm.sh/chart: torrent-http-proxy-0.1.0
+     app.kubernetes.io/instance: torrent-http-proxy
+     app.kubernetes.io/managed-by: Helm
+ spec:
+   selector:
+     matchLabels:
+       app.kubernetes.io/name: torrent-http-proxy
+       app.kubernetes.io/instance: torrent-http-proxy
+   template:
+     metadata:
+       annotations:
+         checksum/config: bf6f461c2e81cc0b09a1871aa046d19581ce5687772e0d3299259d8dd1653ad8
+       labels:
+         app.kubernetes.io/name: torrent-http-proxy
+         app.kubernetes.io/instance: torrent-http-proxy
+     spec:
+       volumes:
+         - name: config-volume
+           configMap:
+             name: torrent-http-proxy
+       containers:
+         - name: torrent-http-proxy
+           image: "webtor/torrent-http-proxy:latest"
+           imagePullPolicy: IfNotPresent
+           volumeMounts:
+             - name: config-volume
+               mountPath: /etc/config
+           env:
+             - name: JOB_NODE_AFFINITY_KEY
+               value: ""
+             - name: JOB_NODE_AFFINITY_VALUE
+               value: ""
+             - name: SEEDER_IMAGE
+               value: "webtor/torrent-web-seeder:latest"
+             - name: SEEDER_CPU_REQUESTS
+               value: ""
+             - name: SEEDER_CPU_LIMITS
+               value: ""
+             - name: TRANSCODER_IMAGE
+               value: "webtor/content-transcoder:latest"
+             - name: TRANSCODER_CPU_REQUESTS
+               value: ""
+             - name: TRANSCODER_CPU_LIMITS
+               value: ""
+             - name: WEB_ORIGIN_HOST_REDIRECT_FLAG
+               value: ""
+             - name: WEB_ORIGIN_HOST_REDIRECT_PREFIX_FLAG
+               value: "abra--"
+           ports:
+             - name: http
+               containerPort: 8080
+               protocol: TCP
+             - name: httpprobe
+               containerPort: 8081
+               protocol: TCP
+             - name: grpc
+               containerPort: 50051
+               protocol: TCP
+           livenessProbe:
+             httpGet:
+               path: /liveness
+               port: httpprobe
+           readinessProbe:
+             httpGet:
+               path: /readiness
+               port: httpprobe
+           resources:
+             {}
webtor, torrent-http-proxy, Service (v1) has been added:
-
+ # Source: torrent-http-proxy/templates/service.yaml
+ apiVersion: v1
+ kind: Service
+ metadata:
+   name: torrent-http-proxy
+   labels:
+     app.kubernetes.io/name: torrent-http-proxy
+     helm.sh/chart: torrent-http-proxy-0.1.0
+     app.kubernetes.io/instance: torrent-http-proxy
+     app.kubernetes.io/managed-by: Helm
+ spec:
+   type: NodePort
+   ports:
+     - port: 80
+       targetPort: http
+       protocol: TCP
+       name: http
+     - port: 50051
+       targetPort: grpc
+       protocol: TCP
+       name: grpc
+   selector:
+     app.kubernetes.io/name: torrent-http-proxy
+     app.kubernetes.io/instance: torrent-http-proxy

********************

        Release was not present in Helm.  Diff will show entire contents as new.

********************
webtor, magnet2torrent, Deployment (apps) has been added:
-
+ # Source: magnet2torrent/templates/deployment.yaml
+ apiVersion: apps/v1
+ kind: Deployment
+ metadata:
+   name: magnet2torrent
+   labels:
+     app.kubernetes.io/name: magnet2torrent
+     helm.sh/chart: magnet2torrent-0.1.0
+     app.kubernetes.io/instance: magnet2torrent
+     app.kubernetes.io/managed-by: Helm
+ spec:
+   replicas: 1
+   selector:
+     matchLabels:
+       app.kubernetes.io/name: magnet2torrent
+       app.kubernetes.io/instance: magnet2torrent
+   template:
+     metadata:
+       labels:
+         app.kubernetes.io/name: magnet2torrent
+         app.kubernetes.io/instance: magnet2torrent
+     spec:
+       containers:
+         - name: magnet2torrent
+           image: "webtor/magnet2torrent:latest"
+           imagePullPolicy: IfNotPresent
+           ports:
+             - name: grpc
+               containerPort: 50051
+               protocol: TCP
+           livenessProbe:
+             tcpSocket:
+               port: grpc
+           readinessProbe:
+             tcpSocket:
+               port: grpc
+           resources:
+             {}
webtor, magnet2torrent, Service (v1) has been added:
-
+ # Source: magnet2torrent/templates/service.yaml
+ apiVersion: v1
+ kind: Service
+ metadata:
+   name: magnet2torrent
+   labels:
+     app.kubernetes.io/name: magnet2torrent
+     helm.sh/chart: magnet2torrent-0.1.0
+     app.kubernetes.io/instance: magnet2torrent
+     app.kubernetes.io/managed-by: Helm
+ spec:
+   type: ClusterIP
+   ports:
+     - port: 50051
+       targetPort: grpc
+       protocol: TCP
+       name: grpc
+   selector:
+     app.kubernetes.io/name: magnet2torrent
+     app.kubernetes.io/instance: magnet2torrent

********************

        Release was not present in Helm.  Diff will show entire contents as new.

********************
webtor, srt2vtt, Deployment (apps) has been added:
-
+ # Source: srt2vtt/templates/deployment.yaml
+ apiVersion: apps/v1
+ kind: Deployment
+ metadata:
+   name: srt2vtt
+   labels:
+     app.kubernetes.io/name: srt2vtt
+     helm.sh/chart: srt2vtt-0.1.0
+     app.kubernetes.io/instance: srt2vtt
+     app.kubernetes.io/version: "1.0"
+     app.kubernetes.io/managed-by: Helm
+ spec:
+   replicas: 1
+   selector:
+     matchLabels:
+       app.kubernetes.io/name: srt2vtt
+       app.kubernetes.io/instance: srt2vtt
+   template:
+     metadata:
+       labels:
+         app.kubernetes.io/name: srt2vtt
+         app.kubernetes.io/instance: srt2vtt
+     spec:
+       containers:
+         - name: srt2vtt
+           securityContext:
+             null
+           image: "webtor/srt2vtt:latest"
+           imagePullPolicy: IfNotPresent
+           ports:
+             - name: http
+               containerPort: 8080
+               protocol: TCP
+             - name: httpprobe
+               containerPort: 8081
+               protocol: TCP
+           livenessProbe:
+             httpGet:
+               path: /liveness
+               port: httpprobe
+           readinessProbe:
+             httpGet:
+               path: /readiness
+               port: httpprobe
+           resources:
+             {}
webtor, srt2vtt, Service (v1) has been added:
-
+ # Source: srt2vtt/templates/service.yaml
+ apiVersion: v1
+ kind: Service
+ metadata:
+   name: srt2vtt
+   labels:
+     app.kubernetes.io/name: srt2vtt
+     helm.sh/chart: srt2vtt-0.1.0
+     app.kubernetes.io/instance: srt2vtt
+     app.kubernetes.io/version: "1.0"
+     app.kubernetes.io/managed-by: Helm
+ spec:
+   type: ClusterIP
+   ports:
+     - port: 80
+       targetPort: http
+       protocol: TCP
+       name: http
+   selector:
+     app.kubernetes.io/name: srt2vtt
+     app.kubernetes.io/instance: srt2vtt

in ./helmfile.yaml: command "/usr/local/bin/helm" exited with non-zero status:

PATH:
  /usr/local/bin/helm

ARGS:
  0: helm (4 bytes)
  1: diff (4 bytes)
  2: upgrade (7 bytes)
  3: --reset-values (14 bytes)
  4: --allow-unreleased (18 bytes)
  5: redis (5 bytes)
  6: stable/redis (12 bytes)
  7: --version (9 bytes)
  8: 9.5.0 (5 bytes)
  9: --namespace (11 bytes)
  10: webtor (6 bytes)
  11: --values (8 bytes)
  12: /tmp/values127266497 (20 bytes)
  13: --values (8 bytes)
  14: /tmp/values276883756 (20 bytes)
  15: --values (8 bytes)
  16: /tmp/values266262171 (20 bytes)
  17: --detailed-exitcode (19 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: Failed to render chart: exit status 1: Error: failed to download "stable/redis" (hint: running `helm repo update` may help)
  Error: plugin "diff" exited with error

COMBINED OUTPUT:
  ********************
        Release was not present in Helm.  Diff will show entire contents as new.
  ********************
  Error: Failed to render chart: exit status 1: Error: failed to download "stable/redis" (hint: running `helm repo update` may help)
  Error: plugin "diff" exited with error

**Comment by wlasser** [comment]
As i am remember - there is trouble related to you minikube/helm version. Just install all software with versions presented in Readme.

**Comment by vintikzzz** [comment]
Hi! I have updated README.md and added script to install webtor on Ubuntu. Maybe this could help
I any case I need version of helm and helmfile. As @wlasser mentioned install process is really sensitive to specific versions.
