### ISSUE TITLE
[Feature][Request][Question] Is it possible to software limit speed of webtor clients?

### ISSUE THREAD

**Issue by wlasser** [webtor-io/helm-charts#6]
Hello @vintikzzz!
I can limit rate speed with iptables/iproutes, but there is question about software limitation.
Maybe wrong repositories, and this related to sdk, sorry.

**Comment by vintikzzz** [comment]
Hi @wlasser!
Finally, I added some notes about this:
https://github.com/webtor-io/helm-charts/blob/master/README.md#secure-your-api
