### ISSUE TITLE
Problem with short way installation

### ISSUE THREAD

**Issue by vahidkaargar** [webtor-io/helm-charts#8]
Problem with short way installation:
![Capture](https://user-images.githubusercontent.com/3912242/107881816-35990700-6efb-11eb-99de-8aa789bada92.PNG)
Any solution?

**Comment by vintikzzz** [comment]
Can you provide full listing?

**Comment by vahidkaargar** [comment]
`Comparing release=torrent-archiver, chart=webtor/torrent-archiver
Comparing release=external-proxy, chart=webtor/external-proxy
Comparing release=content-prober, chart=webtor/content-prober
Comparing release=torrent-http-proxy, chart=webtor/torrent-http-proxy
Comparing release=redis, chart=stable/redis
Comparing release=magnet2torrent, chart=webtor/magnet2torrent
Comparing release=srt2vtt, chart=webtor/srt2vtt
Comparing release=job-cleaner, chart=webtor/job-cleaner
Comparing release=torrent-store, chart=webtor/torrent-store
Comparing release=video-info, chart=webtor/video-info
in ./helmfile.yaml: 10 errors:
err 0: failed processing release torrent-http-proxy: microk8s.helm exited with status 1:
  Error: unknown command "diff" for "helm"
  Run 'helm --help' for usage.
err 1: failed processing release srt2vtt: microk8s.helm exited with status 1:
  Error: unknown command "diff" for "helm"
  Run 'helm --help' for usage.
err 2: failed processing release magnet2torrent: microk8s.helm exited with status 1:
  Error: unknown command "diff" for "helm"
  Run 'helm --help' for usage.
err 3: failed processing release external-proxy: microk8s.helm exited with status 1:
  Error: unknown command "diff" for "helm"
  Run 'helm --help' for usage.
err 4: failed processing release torrent-archiver: microk8s.helm exited with status 1:
  Error: unknown command "diff" for "helm"
  Run 'helm --help' for usage.
err 5: failed processing release redis: microk8s.helm exited with status 1:
  Error: unknown command "diff" for "helm"
  Run 'helm --help' for usage.
err 6: failed processing release content-prober: microk8s.helm exited with status 1:
  Error: unknown command "diff" for "helm"
  Run 'helm --help' for usage.
err 7: failed processing release torrent-store: microk8s.helm exited with status 1:
  Error: unknown command "diff" for "helm"
  Run 'helm --help' for usage.
err 8: failed processing release video-info: microk8s.helm exited with status 1:
  Error: unknown command "diff" for "helm"
  Run 'helm --help' for usage.
err 9: failed processing release job-cleaner: microk8s.helm exited with status 1:
  Error: unknown command "diff" for "helm"
  Run 'helm --help' for usage.
Error from server (NotFound): namespaces "webtor" not found
Error from server (NotFound): namespaces "webtor" not found`

**Comment by vahidkaargar** [comment]
Comparing release=torrent-archiver, chart=webtor/torrent-archiver
Comparing release=external-proxy, chart=webtor/external-proxy
Comparing release=content-prober, chart=webtor/content-prober
Comparing release=torrent-http-proxy, chart=webtor/torrent-http-proxy
Comparing release=redis, chart=stable/redis
Comparing release=magnet2torrent, chart=webtor/magnet2torrent
Comparing release=srt2vtt, chart=webtor/srt2vtt
Comparing release=job-cleaner, chart=webtor/job-cleaner
Comparing release=torrent-store, chart=webtor/torrent-store
Comparing release=video-info, chart=webtor/video-info
in ./helmfile.yaml: 10 errors:
err 0: failed processing release torrent-http-proxy: microk8s.helm exited with status 1:
  Error: unknown command "diff" for "helm"
  Run 'helm --help' for usage.
err 1: failed processing release srt2vtt: microk8s.helm exited with status 1:
  Error: unknown command "diff" for "helm"
  Run 'helm --help' for usage.
err 2: failed processing release magnet2torrent: microk8s.helm exited with status 1:
  Error: unknown command "diff" for "helm"
  Run 'helm --help' for usage.
err 3: failed processing release external-proxy: microk8s.helm exited with status 1:
  Error: unknown command "diff" for "helm"
  Run 'helm --help' for usage.
err 4: failed processing release torrent-archiver: microk8s.helm exited with status 1:
  Error: unknown command "diff" for "helm"
  Run 'helm --help' for usage.
err 5: failed processing release redis: microk8s.helm exited with status 1:
  Error: unknown command "diff" for "helm"
  Run 'helm --help' for usage.
err 6: failed processing release content-prober: microk8s.helm exited with status 1:
  Error: unknown command "diff" for "helm"
  Run 'helm --help' for usage.
err 7: failed processing release torrent-store: microk8s.helm exited with status 1:
  Error: unknown command "diff" for "helm"
  Run 'helm --help' for usage.
err 8: failed processing release video-info: microk8s.helm exited with status 1:
  Error: unknown command "diff" for "helm"
  Run 'helm --help' for usage.
err 9: failed processing release job-cleaner: microk8s.helm exited with status 1:
  Error: unknown command "diff" for "helm"
  Run 'helm --help' for usage.
Error from server (NotFound): namespaces "webtor" not found
Error from server (NotFound): namespaces "webtor" not found

**Comment by vintikzzz** [comment]
I don't see the beginning.
Listing should start from first command:
```
curl https://raw.githubusercontent.com/webtor-io/helm-charts/master/scripts/get-webtor.sh | sh
```

**Comment by vahidkaargar** [comment]
Here is from the first

[console.txt](https://github.com/webtor-io/helm-charts/files/5995918/console.txt)

**Comment by vintikzzz** [comment]
@vahidkaargar I've updated install script, now it should fine. If you will have any problems just reopen issue.

**Comment by vahidkaargar** [comment]
Thank you but its not resolved
[Terminal.txt](https://github.com/webtor-io/helm-charts/files/6002263/Terminal.txt)

**Comment by vintikzzz** [comment]
try to uninstall with `sudo snap remove microk8s` and then run script again

**Comment by vahidkaargar** [comment]
I did it but the same result
[microk8s.removed.and.install.txt](https://github.com/webtor-io/helm-charts/files/6005563/microk8s.removed.and.install.txt)

**Comment by vintikzzz** [comment]
can you made helm plugins directory like this?
```
sudo mkdir $(microk8s helm home)/plugins
```
and restart script?
...or you can just restart script, I've already added this step to it.

**Comment by vahidkaargar** [comment]
Its did not any different result. I can give you ssh information if you don't mind wasting your time on me ;)
[Terminal.txt](https://github.com/webtor-io/helm-charts/files/6012630/Terminal.txt)

**Comment by vintikzzz** [comment]
@vahidkaargar it would be great )
can you find me in telegram as @vintikzzzz ?

**Comment by vahidkaargar** [comment]
My pleasure

**Comment by h0lybyte** [comment]
I ran into the same issue, if you guys found a solution, let me know!
